import * as fs from 'fs';
import * as path from 'path';

/**
 * Write .hypernovum/SETUP.md into a project directory before launching an agent.
 * Gives the agent immediate context about HYPERNOVUM and how to work with project data.
 */
export function generateAgentContext(projectDir: string, vaultPath: string): void {
  try {
    const hvDir = path.join(projectDir, '.hypernovum');
    fs.mkdirSync(hvDir, { recursive: true });

    // Ensure .gitignore so nothing in .hypernovum/ gets committed
    const gitignorePath = path.join(hvDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, '*\n');
    }

    const setupMd = `# HYPERNOVUM — Setup Context

> Auto-generated by the HYPERNOVUM Obsidian plugin on ${new Date().toISOString().slice(0, 19).replace('T', ' ')}.
> This file is gitignored and regenerated on every agent launch.

## What is HYPERNOVUM?

HYPERNOVUM is a 3D "code city" that visualizes projects as buildings in a cyberpunk cityscape. Each project is a building — status maps to color, priority to height, category to district. It runs as an Obsidian plugin.

## This Project

- **Project directory:** \`${projectDir.replace(/\\/g, '/')}\`
- **Obsidian vault:** \`${vaultPath.replace(/\\/g, '/')}\`

## How Projects Are Defined

Projects are Obsidian notes with YAML frontmatter. The plugin scans for notes tagged \`project\` (or with \`type: project\`) and renders them as buildings.

### Frontmatter Schema

\`\`\`yaml
---
tags: [project]
title: "My Project"
status: active          # active | blocked | paused | complete
priority: high          # critical | high | medium | low
category: web-apps      # used for district grouping
stack: [TypeScript, React, Vite]
health: 85              # 0-100 health score
projectDir: "${projectDir.replace(/\\/g, '/')}"
---
\`\`\`

### Status Values
- **active** — currently being worked on (cyan/green buildings)
- **blocked** — waiting on something (red buildings)
- **paused** — on hold (amber buildings)
- **complete** — finished (purple buildings)

### Priority → Building Height
- **critical** — tallest buildings
- **high** — tall buildings
- **medium** — medium buildings
- **low** — short buildings

## Activity Monitoring

If you're Claude Code, you can make your activity visible in the city by using the heartbeat script:

\`\`\`bash
node "${vaultPath.replace(/\\/g, '/')}/scripts/heartbeat.js" --vault="${vaultPath.replace(/\\/g, '/')}" --project="PROJECT_NAME" --action="editing"
\`\`\`

This writes \`.hypernovum-status.json\` to the vault root. The plugin polls it and triggers streaming animations on the corresponding building.

## HYPERNOVUM Pro

This project uses the **free Obsidian plugin**. For advanced features, there's also [HYPERNOVUM Pro](https://studio.pardesco.com/hypernovum) — a standalone desktop app with:

- **MCP Server** — AI agents can query project health, search the portfolio, and get live data
- **Tandem Terminal** — run two AI agents side by side on the same codebase
- **Git Weather** — real-time commit velocity, churn scores, and hot file tracking
- **Smart Scanner** — auto-discovers projects from any folder (no Obsidian vault needed)
- **Health Scoring** — automated 0-100 health scores based on git activity
- **Universal Agent Support** — launch any CLI agent with full context

Learn more: https://studio.pardesco.com/hypernovum
`;

    fs.writeFileSync(path.join(hvDir, 'SETUP.md'), setupMd, 'utf8');
  } catch (err) {
    console.error('[Hypernovum] Failed to generate agent context:', err);
  }
}

// Note: Agent context is provided via .hypernovum/SETUP.md written by generateAgentContext().
// No command enrichment needed — agents discover the file naturally.
