import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
`;

const prod = process.argv[2] === 'production';

// Output to vault's plugin folder (two levels up from packages/obsidian-plugin)
const vaultPluginDir = path.resolve(__dirname, '../../.obsidian/plugins/obsidian-hypernovum');

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: [path.resolve(__dirname, 'src/main.ts')],
  bundle: true,
  plugins: [
    {
      name: 'resolve-core',
      setup(build) {
        build.onResolve({ filter: /^@hypernovum\/core$/ }, args => {
          return { path: path.resolve(__dirname, '../core/src/index.ts') };
        });
      },
    },
  ],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  // @hypernovum/core is NOT external — it gets bundled into the plugin
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.resolve(vaultPluginDir, 'main.js'),
  minify: prod,
  loader: {
    '.vert': 'text',
    '.frag': 'text',
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
